### ISSUE TITLE
per-interface option

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap-plugin-collector-interface#13]
The info suggests that the metrics are per-interface. But when trying to collect only from the eth[0-9] interface, is impossible. The 'snapctl metric list' suggests only '*' wildcard is possible.

So either the info should be changed, or the user should be allowed to indicate if he wants to collect the metrics from a single interface. My vote is for the latter. @intelsdi-x/plugin-maintainers

**Comment by IzabellaRaulin** [comment]
This issue is related to snap#654 
cc: @intelsdi-x/snap-maintainers
