### ISSUE TITLE
released version of plugin (for v0.15.0-beta) produces error on task creation

### ISSUE THREAD

**Issue by lanejlanej** [intelsdi-x/snap-plugin-collector-interface#14]
task create on Amazon linux gave this error:

open /tmp/522571651/snap-plugin-collector-interface: no such file or directory

When plugin built from source task creation works fine, and plugin functions as expected.

**Comment by jcooklin** [comment]
Thanks for the comment.  Building from master is the suggestion we would have given.  

Some related info
* We don't have plans to update the previous releases 
* A v.0.16 release will be landing shortly
 * The issue you saw should be resolved in this release
 * After the 0.16 release we will publish plugins on merge to master.  This will enabling downloading the latest plugin directly from the [plugin catalog](https://github.com/intelsdi-x/snap/blob/master/docs/PLUGIN_CATALOG.md)  
   * We will publish to http://snap.ci.snap-telemetry.io
